/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as LegalNoticesRouteImport } from './routes/legal-notices'
import { Route as NcrpRouteImport } from './routes/ncrp'
import { Route as VaspRouteImport } from './routes/vasp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticesRoute = LegalNoticesRouteImport.update({
  id: '/legal-notices',
  path: '/legal-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const NcrpRoute = NcrpRouteImport.update({
  id: '/ncrp',
  path: '/ncrp',
  getParentRoute: () => rootRouteImport,
} as any)
const VaspRoute = VaspRouteImport.update({
  id: '/vasp',
  path: '/vasp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/investigations': typeof InvestigationsRoute
  '/legal-notices': typeof LegalNoticesRoute
  '/ncrp': typeof NcrpRoute
  '/vasp': typeof VaspRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/investigations': typeof InvestigationsRoute
  '/legal-notices': typeof LegalNoticesRoute
  '/ncrp': typeof NcrpRoute
  '/vasp': typeof VaspRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/investigations': typeof InvestigationsRoute
  '/legal-notices': typeof LegalNoticesRoute
  '/ncrp': typeof NcrpRoute
  '/vasp': typeof VaspRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auth'
    | '/dashboard'
    | '/investigations'
    | '/legal-notices'
    | '/ncrp'
    | '/vasp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auth'
    | '/dashboard'
    | '/investigations'
    | '/legal-notices'
    | '/ncrp'
    | '/vasp'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/auth'
    | '/dashboard'
    | '/investigations'
    | '/legal-notices'
    | '/ncrp'
    | '/vasp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  InvestigationsRoute: typeof InvestigationsRoute
  LegalNoticesRoute: typeof LegalNoticesRoute
  NcrpRoute: typeof NcrpRoute
  VaspRoute: typeof VaspRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-notices': {
      id: '/legal-notices'
      path: '/legal-notices'
      fullPath: '/legal-notices'
      preLoaderRoute: typeof LegalNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncrp': {
      id: '/ncrp'
      path: '/ncrp'
      fullPath: '/ncrp'
      preLoaderRoute: typeof NcrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vasp': {
      id: '/vasp'
      path: '/vasp'
      fullPath: '/vasp'
      preLoaderRoute: typeof VaspRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  InvestigationsRoute: InvestigationsRoute,
  LegalNoticesRoute: LegalNoticesRoute,
  NcrpRoute: NcrpRoute,
  VaspRoute: VaspRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
